#!/usr/bin/env bash
# gemma-4-31b-it-uncensored — vLLM single-node controller
# Model:    Iambackup/gemma-4-31B-it-uncensored @ 9e8e8510f885beb7bc514df9ff5c5332224c0a36
# Target:   this-machine | Generated by LMDS 0.1.0 (llm:openai-compat/gemma-4-26b-a4b-it-q8xl)
# Standard: dgx-spark-controllers v3.0.0 controller contract
set -Eeuo pipefail

SCRIPT_VERSION="${SCRIPT_VERSION:-3.1.0}"
MODEL_LABEL="${MODEL_LABEL:-Gemma-4-31B Uncensored (Iambackup)}"
RUNTIME_LABEL="${RUNTIME_LABEL:-vLLM (Docker)}"
MODEL_FEATURES="${MODEL_FEATURES:-text · tools · uncensored}"

# ============================ CONFIG (แก้ได้) ============================
MODEL_ID="Iambackup/gemma-4-31B-it-uncensored"
MODEL_REVISION="9e8e8510f885beb7bc514df9ff5c5332224c0a36"
SERVED_MODEL_NAME="gemma-4-31b-it-uncensored"
VLLM_IMAGE="vllm/vllm-openai:latest"
CONTAINER_NAME="${CONTAINER_NAME:-lmds-gemma-4-31b-it-uncensored}"

MAX_MODEL_LEN="${MAX_MODEL_LEN:-32768}"
API_HOST="${API_HOST:-0.0.0.0}"
API_PORT="${API_PORT:-8000}"
API_KEY="${API_KEY:-}"
ADVERTISE_IP="${ADVERTISE_IP:-}"
ADVERTISE_INTERFACE="${ADVERTISE_INTERFACE:-}"
ROUTE_PROBE_IP="${ROUTE_PROBE_IP:-1.1.1.1}"

GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.85}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-4}"
CLIENT_OUTPUT="${CLIENT_OUTPUT:-8192}"
CLIENT_INPUT="${CLIENT_INPUT:-auto}"
TEMPLATE_OVERHEAD_TOKENS="2048"

HF_HOME="${HF_HOME:-${HOME}/.cache/huggingface}"
RUN_DIR="${RUN_DIR:-${HOME}/.lmds/run/gemma-4-31b-it-uncensored}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-2049}"
# ========================================================================

die() { echo "ERROR: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }

validate_numbers() {
  [[ "$API_PORT" =~ ^[0-9]+$ ]] && (( API_PORT >= 1 && API_PORT <= 65535 )) ||
    die "invalid API_PORT: $API_PORT"
  [[ "$MAX_MODEL_LEN" =~ ^[0-9]+$ ]] && (( MAX_MODEL_LEN > 0 )) ||
    die "invalid context: $MAX_MODEL_LEN"
  [[ "$CLIENT_OUTPUT" =~ ^[0-9]+$ ]] && (( CLIENT_OUTPUT > 0 )) ||
    die "invalid CLIENT_OUTPUT: $CLIENT_OUTPUT"
}

# ── Branding / info ───────────────────────────────────────────────────────────
banner() {
  cat <<'ART'

   ____   ____ __  __    ____                   _
  |  _ \ / ___|\ \/ /   / ___| _ __   __ _ _ __| | __
  | | | | |  _  \  /    \___ \| '_ \ / _` | '__| |/ /
  | |_| | |_| | /  \     ___) | |_) | (_| | |  |   <
  |____/ \____|/_/\_\   |____/| .__/ \__,_|_|  |_|\_\
                              |_|
ART
  printf '       =[ DGX Spark Controller · v%s ]\n' "${SCRIPT_VERSION}"
  printf '+ -- --=[ %s ]\n'   "${MODEL_LABEL}"
  printf '+ -- --=[ %s · %s ]\n' "${RUNTIME_LABEL}" "${MODEL_FEATURES}"
  printf '+ -- --=[ Designed by neronain · fb.com/neronain.minidev ]\n\n'
}

# Show which model this controller serves, its port, features, and whether it is up.
info() {
  banner
  local ip url state
  ip="$(detect_advertise_ip 2>/dev/null || true)"; [[ -n "$ip" ]] || ip="${API_HOST}"
  url="http://${ip}:${API_PORT}/v1"
  state="stopped"
  if curl -fsS -m 2 "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
    state="RUNNING"
  fi
  printf '  Model     : %s\n'            "${MODEL_LABEL}"
  printf '  Model ID  : %s\n'            "${MODEL_ID:-${HF_REPO:-${REPO_ID:-n/a}}}"
  printf '  Runtime   : %s\n'            "${RUNTIME_LABEL}"
  printf '  Features  : %s\n'            "${MODEL_FEATURES}"
  printf '  Context   : %s tokens\n'     "${MAX_MODEL_LEN:-${CTX_SIZE:-n/a}}"
  printf '  API (v1)  : %s\n'            "${url}"
  printf '  State     : %s  (port %s)\n\n' "${state}" "${API_PORT}"
}

detect_advertise_ip() {
  if [[ -n "$ADVERTISE_IP" ]]; then printf '%s' "$ADVERTISE_IP"; return; fi
  if [[ -n "$ADVERTISE_INTERFACE" ]]; then
    ip -4 -o addr show dev "$ADVERTISE_INTERFACE" scope global |
      awk 'NR == 1 { split($4, a, "/"); print a[1] }'
    return
  fi
  local route_src
  route_src="$(ip -4 route get "$ROUTE_PROBE_IP" 2>/dev/null |
    awk '{ for (i=1; i<=NF; i++) if ($i=="src") { print $(i+1); exit } }')"
  if [[ -n "$route_src" ]]; then printf '%s' "$route_src"; return; fi
  hostname -I 2>/dev/null | awk '{print $1}'
}

parse_options() {
  REMAINING_ARGS=()
  while (( $# )); do
    case "$1" in
      --context)        MAX_MODEL_LEN="$2"; shift 2 ;;
      --context=*)      MAX_MODEL_LEN="${1#*=}"; shift ;;
      --port)           API_PORT="$2"; shift 2 ;;
      --port=*)         API_PORT="${1#*=}"; shift ;;
      --bind)           API_HOST="$2"; shift 2 ;;
      --bind=*)         API_HOST="${1#*=}"; shift ;;
      --advertise-ip)   ADVERTISE_IP="$2"; shift 2 ;;
      --advertise-ip=*) ADVERTISE_IP="${1#*=}"; shift ;;
      --interface)      ADVERTISE_INTERFACE="$2"; shift 2 ;;
      --interface=*)    ADVERTISE_INTERFACE="${1#*=}"; shift ;;
      --client-input)   CLIENT_INPUT="$2"; shift 2 ;;
      --client-input=*) CLIENT_INPUT="${1#*=}"; shift ;;
      --client-output)  CLIENT_OUTPUT="$2"; shift 2 ;;
      --client-output=*) CLIENT_OUTPUT="${1#*=}"; shift ;;
      *) REMAINING_ARGS+=("$1"); shift ;;
    esac
  done
  validate_numbers
}

network_info() {
  echo "Bind:      ${API_HOST}:${API_PORT}"
  echo "Endpoint:  http://$(detect_advertise_ip):${API_PORT}/v1"
  echo "Model:     ${SERVED_MODEL_NAME}"
  echo "Context:   ${MAX_MODEL_LEN}"
}

snapshot_dir() {
  printf '%s/hub/models--%s/snapshots/%s' "$HF_HOME" "${MODEL_ID//\//--}" "$MODEL_REVISION"
}

check_gpu() {
  need docker
  local out
  out="$(docker run --rm --gpus all --entrypoint nvidia-smi "$VLLM_IMAGE" -L 2>&1)" ||
    die "GPU ใน container ใช้ไม่ได้: $out"
  echo "$out"
}

download() {
  need docker
  mkdir -p "$HF_HOME"
  docker run --rm \
    --user "$(id -u):$(id -g)" \
    -e HOME=/tmp -e HF_HOME=/cache \
    ${HF_TOKEN:+-e HF_TOKEN="$HF_TOKEN"} \
    -v "${HF_HOME}:/cache" \
    --entrypoint python3 "$VLLM_IMAGE" -c "
from huggingface_hub import snapshot_download
snapshot_download(repo_id='${MODEL_ID}', revision='${MODEL_REVISION}', cache_dir=None)
print('download complete')
"
}

verify_files() {
  local snap
  snap="$(snapshot_dir)"
  [[ -d "$snap" ]] || die "ยังไม่ได้ download (ไม่พบ $snap) — รัน: $0 download"
  local f
  for f in config.json model.safetensors.index.json; do
    [[ -e "${snap}/${f}" ]] || die "ไฟล์จำเป็นหายไป: ${f}"
  done
  local broken
  broken="$(find -L "$snap" -type l 2>/dev/null || true)"
  [[ -z "$broken" ]] || die "พบ symlink เสียใน cache: $broken"
  echo "verify-files: OK (${snap})"
}

port_in_use() {
  local out
  out="$(docker ps --filter "publish=${API_PORT}" --format '{{.Names}}' 2>/dev/null || true)"
  [[ -n "$out" ]]
}

write_meta() {
  # ลงทะเบียนกับ lmds fleet (~/.lmds/run) — ให้ lmds ps/stop/logs เห็นเซิร์ฟเวอร์ตัวนี้
  mkdir -p "$RUN_DIR"
  local script_path
  script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
  cat > "${RUN_DIR}/server.meta" <<EOF
slug=gemma-4-31b-it-uncensored
model=${SERVED_MODEL_NAME}
model_id=${MODEL_ID}
engine=vllm
mode=docker
port=${API_PORT}
container=${CONTAINER_NAME}
pid_file=
controller=${script_path}
started_at=$(date +%Y-%m-%dT%H:%M:%S)
EOF
}

start() {
  need docker
  local existing
  existing="$(docker ps -a --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' 2>/dev/null || true)"
  [[ -z "$existing" ]] || die "container ${CONTAINER_NAME} มีอยู่แล้ว — รัน: $0 stop ก่อน"
  check_gpu >/dev/null
  verify_files

  # สร้าง argument เป็น array ทั้งหมด — ห้ามใช้ line continuation คร่อม template block
  local serve_args=(
    serve "$MODEL_ID"
    --revision "$MODEL_REVISION"
    --served-model-name "$SERVED_MODEL_NAME"
    --max-model-len "$MAX_MODEL_LEN"
    --gpu-memory-utilization "$GPU_MEMORY_UTILIZATION"
    --max-num-seqs "$MAX_NUM_SEQS"
    --host "$API_HOST"
    --port "$API_PORT"
  )






  local docker_args=(
    run -d --name "$CONTAINER_NAME"
    --network host --ipc host --gpus all
    -v "${HF_HOME}:/root/.cache/huggingface"
  )
  if [[ -n "${HF_TOKEN:-}" ]]; then docker_args+=(-e "HF_TOKEN=${HF_TOKEN}"); fi
  if [[ -n "$API_KEY" ]]; then docker_args+=(-e "VLLM_API_KEY=${API_KEY}"); fi
  docker_args+=(--entrypoint vllm "$VLLM_IMAGE")

  docker "${docker_args[@]}" "${serve_args[@]}"

  write_meta
  wait_health
  echo "started: $(detect_advertise_ip):${API_PORT} (${SERVED_MODEL_NAME})"
  network_info
}

wait_health() {
  local waited=0
  echo "รอ /health (สูงสุด ${HEALTH_TIMEOUT}s — โหลดโมเดลใหญ่ใช้เวลานาน)..."
  until curl -fsS "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; do
    local running
    running="$(docker ps --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' 2>/dev/null || true)"
    [[ -n "$running" ]] || die "container หยุดก่อน health ผ่าน — ดู: $0 logs"
    if (( waited >= HEALTH_TIMEOUT )); then
      echo "ยังไม่ health ภายใน ${HEALTH_TIMEOUT}s — container ยังโหลดต่ออยู่ ไม่ได้ถูกหยุด" >&2
      echo "รอต่อ:      $0 wait-health" >&2
      echo "ดูคืบหน้า:   $0 logs 100" >&2
      echo "รอบหน้ารอนานขึ้น: HEALTH_TIMEOUT=3600 $0 start" >&2
      exit 1
    fi
    sleep 5
    waited=$(( waited + 5 ))
  done
}

stop() { docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true; echo "stopped ${CONTAINER_NAME}"; }

status() {
  docker ps -a --filter "name=^${CONTAINER_NAME}$"
  if curl -fsS "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
    echo "API: healthy"
    curl -fsS ${API_KEY:+-H "Authorization: Bearer $API_KEY"} \
      "http://127.0.0.1:${API_PORT}/v1/models" 2>/dev/null || true
    echo ""
  else
    echo "API: not responding"
  fi
}

logs() { docker logs --tail "${1:-300}" "$CONTAINER_NAME"; }

client_config() {
  local input_budget
  if [[ "$CLIENT_INPUT" == "auto" ]]; then
    input_budget=$(( MAX_MODEL_LEN - CLIENT_OUTPUT - TEMPLATE_OVERHEAD_TOKENS ))
  else
    input_budget="$CLIENT_INPUT"
  fi
  (( input_budget > 0 )) || die "context เล็กเกิน: input budget = ${input_budget}"
  cat <<EOF
{
  "base_url": "http://$(detect_advertise_ip):${API_PORT}/v1",
  "model": "${SERVED_MODEL_NAME}",
  "api_key": "${API_KEY:-not-required}",
  "max_input_tokens": ${input_budget},
  "max_output_tokens": ${CLIENT_OUTPUT},
  "server_context": ${MAX_MODEL_LEN}
}
EOF
}

test_text() {
  curl -fsS "http://127.0.0.1:${API_PORT}/v1/chat/completions" \
    ${API_KEY:+-H "Authorization: Bearer $API_KEY"} \
    -H "Content-Type: application/json" \
    -d "{
      \"model\": \"${SERVED_MODEL_NAME}\",
      \"messages\": [{\"role\": \"user\", \"content\": \"ตอบสั้น ๆ: 2+2 เท่ากับเท่าไร\"}],
      \"max_tokens\": 64
    }"
  echo ""
}

usage() {
  cat <<EOF
Usage: $0 <command> [--context N] [--port N] [--bind ADDR] [--advertise-ip ADDR]
          [--interface NAME] [--client-input N|auto] [--client-output N]

Commands:
  download        ดาวน์โหลดโมเดล (resume ได้, pin revision)
  verify-files    ตรวจไฟล์จำเป็น + symlink
  start           ตรวจ GPU/ไฟล์ แล้วเปิดเซิร์ฟเวอร์ (รอ /health)
  stop | restart  หยุด / restart
  status          สถานะ container + API
  logs [N]        log ล่าสุด N บรรทัด
  client-config   พิมพ์ค่าตั้ง client (JSON) พร้อม token budget
  network-info    bind/endpoint ปัจจุบัน
  test-text       ทดสอบ chat completion หนึ่งครั้ง
  wait-health      รอ /health ต่อ (ใช้เมื่อ start เคย timeout แต่โมเดลยังโหลดอยู่)
EOF
}

parse_options "$@"
set -- ${REMAINING_ARGS[@]+"${REMAINING_ARGS[@]}"}

case "${1:-help}" in
  download)     download ;;
  verify-files) verify_files ;;
  start)        start ;;
  stop)         stop ;;
  restart)      stop; start ;;
  status)       status ;;
  logs)         logs "${2:-300}" ;;
  client-config) client_config ;;
  info|banner) info ;;
  network-info) network_info ;;
  test-text)    test_text ;;
  wait-health)  wait_health ;;
  *)            usage ;;
esac
